
- name: Create a partition on webserver
  hosts: web
  become: true
  become_user: root
  tasks:
    - name: Install lvm2 dependency
      package:
        name: lvm2
        state: present
    - name: create partitions
      block:
        - name: install parted
          package: 
            name: parted
            state: present
    - name: add new partitions
      parted: 
        device: /dev/xvdf
        number: 1
        flags: [ lvm ]
        state: present
        part_end: 100% 
    - name: add new partitions
      parted: 
        device: /dev/xvdg
        number: 1
        flags: [ lvm ]
        state: present
        part_end: 100%
    - name: add new partitions
      parted: 
        device: /dev/xvdh
        number: 1
        flags: [ lvm ]
        state: present
        part_end: 100%
    # - name: pvcreate xvdf1
    #   become: true
    #   shell: pvcreate /dev/xvdf1
    # - name: pvcreate xvdg1
    #   become: true
    #   shell: pvcreate /dev/xvdg1
    # - name: pvcreate xvdh1
    #   become: true
    #   shell: pvcreate /dev/xvdh1
    - name: Create a volume group
      lvg:
        vg: webdata-vg
        pvs: /dev/xvdf1,/dev/xvdg1,/dev/xvdh1
        state: present
    - name: create a logical vol apps-lv with 14G
      lvol: 
        vg: webdata-vg
        lv: apps-lv
        size: 14G
    - name: create a logical vol logs-lv with 14G
      lvol: 
        vg: webdata-vg
        lv: logs-lv
        size: 14G
   

    
    